version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" 
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./front
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}" 
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}" 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
